### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#96]
We can kill a lot of Ansible's complexity by managing our containers with docker-compose: https://docs.docker.com/compose/

A `docker-compose.yml` for a gateway host might look like this:

```yml
cjdns:
  image: hyperboria/cjdns:0.16.3
  cap_add: NET_ADMIN
  devices:
    - /dev/net/tun
  ports:
    - 54321:54321
  volumes:
    - ./cjdns:/etc/cjdns
nginx:
  image: nginx:1.9.3
  net: container:cjdns
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./nginx:/etc/nginx
ipfs:
  image: ipfs/go-ipfs:0.3.8
  net: container:cjdns
  ports:
    - 4001:4001
    - 127.0.0.1:5001:5001
    - 127.0.0.1:8080:8080
  volumes:
    - ./ipfs:/ipfs
  log_driver: none
node_exporter:
  image: prometheus/node_exporter
  net: host
  ports:
    - 127.0.0.1:9100:9100
```

We can probably even generate the various config files locally, and get rid of Ansible for good.
